/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _courbe_horizontale_ULM2w_h_
#define _courbe_horizontale_ULM2w_h_
//---------------------------------------------------------------------------------
extern const unsigned char courbe_horizontale_ULM2w[];
extern const int courbe_horizontale_ULM2w_size;
//---------------------------------------------------------------------------------
#endif //_courbe_horizontale_ULM2w_h_
//---------------------------------------------------------------------------------
