/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _tableoverlay_h_
#define _tableoverlay_h_
//---------------------------------------------------------------------------------
extern unsigned char tableoverlay[];
extern const int tableoverlay_size;
//---------------------------------------------------------------------------------
#endif //_tableoverlay_h_
//---------------------------------------------------------------------------------
