/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _table_2_valeurs_w_h_
#define _table_2_valeurs_w_h_
//---------------------------------------------------------------------------------
extern const unsigned char table_2_valeurs_w[];
extern const int table_2_valeurs_w_size;
//---------------------------------------------------------------------------------
#endif //_table_2_valeurs_w_h_
//---------------------------------------------------------------------------------
